### ISSUE TITLE
Cannot find module progress

### ISSUE THREAD

**Issue by sopicha** [MehediH/Bulksplash#7]
I ran your script and it returned like this:

node index --amount=10 --orientation=landscape --search=line           1 ↵

Welcome to Bulksplash! (Powered by Unsplash.com)

Downloading 10 random images :)
module.js:549
    throw err;
    ^

Error: Cannot find module 'progress'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yoonnie/Bulksplash/index.js:34:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by sopicha** [comment]
just install progress, I can fix now.
Thank for your script!!
